// tests/symbolic-execution/klee/safe-path-resolver.c
//
// C port of safe-path-resolver's lexical-containment kernel.
// Compiled with `clang -emit-llvm -c -g -O0 -Xclang -disable-O0-optnone`
// and run with `klee --check-asserts --warnings-only-too-leak`
//
// This file is illustrative — the actual symbolic-execution target
// is generated by scripts/symbolic-execute.sh from the JS source.

#include <assert.h>
#include <string.h>
#include <stdlib.h>

static int contains_dotdot(const char *s) {
    return strstr(s, "..") != NULL;
}

int is_contained(const char *root, const char *candidate) {
    if (root == NULL || candidate == NULL) return 0;
    if (contains_dotdot(candidate)) return 0;
    size_t rl = strlen(root);
    if (rl == 0) return 0;
    return strncmp(root, candidate, rl) == 0;
}

int main(void) {
    char root[64], candidate[256];
    klee_make_symbolic(root, sizeof(root), "root");
    klee_make_symbolic(candidate, sizeof(candidate), "candidate");
    root[sizeof(root) - 1] = '\0';
    candidate[sizeof(candidate) - 1] = '\0';
    int r = is_contained(root, candidate);
    if (r) {
        // Property: if is_contained, candidate starts with root.
        assert(strncmp(root, candidate, strlen(root)) == 0);
    }
    return r;
}