import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const MAGIC = 'SAL1';
const STATES = Object.freeze(['live', 'retained', 'expired', 'tombstoned', 'deleted']);
const ALLOWED = Object.freeze({ live: Object.freeze(['retained', 'expired', 'tombstoned']), retained: Object.freeze(['live', 'expired', 'tombstoned']), expired: Object.freeze(['retained', 'tombstoned']), tombstoned: Object.freeze(['deleted']), deleted: Object.freeze([]) });
const DEFAULT_LIMITS = Object.freeze({ maxRecords: 4096, maxIdBytes: 256, maxTagBytes: 256, maxReferenceBytes: 512, maxMetadataBytes: 16 * 1024, maxResults: 1024, maxSerializedBytes: 4 * 1024 * 1024 });
class ArtifactLifecycleError extends Error { constructor(code, message) { super(message); this.name = 'ArtifactLifecycleError'; this.code = code; Object.freeze(this); } }
const fail = (code, message) => { throw new ArtifactLifecycleError(code, message); };
const isRecord = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
const byteLength = (value) => Buffer.byteLength(value, 'utf8');
const sha256 = (value) => createHash('sha256').update(value).digest('hex');
function rejectAccessors(value, label) { if (!isRecord(value)) fail('INVALID_DEFINITION', `${label} must be an object`); for (const key of Reflect.ownKeys(value)) { const d = Object.getOwnPropertyDescriptor(value, key); if (typeof key === 'symbol' || !d || !('value' in d)) fail('INVALID_DEFINITION', `${label} contains accessor or symbol key`); } }
function stable(value, label = 'value') { if (Array.isArray(value)) return value.map((item, i) => stable(item, `${label}[${i}]`)); if (isRecord(value)) { rejectAccessors(value, label); const out = {}; for (const key of Object.getOwnPropertyNames(value).sort()) out[key] = stable(value[key], `${label}.${key}`); return out; } if (value === null || typeof value === 'string' || typeof value === 'boolean' || typeof value === 'number') return value; fail('UNSUPPORTED_VALUE', `${label} contains unsupported value`); }
function limitsOf(input = {}) { rejectAccessors(input, 'limits'); const out = { ...DEFAULT_LIMITS, ...input }; for (const v of Object.values(out)) if (!Number.isSafeInteger(v) || v < 1) fail('INVALID_LIMIT', 'Invalid lifecycle limit'); return Object.freeze(out); }
function text(value, label, max) { if (typeof value !== 'string' || !value) fail('INVALID_FIELD', `${label} must be non-empty string`); if (byteLength(value) > max) fail('LIMIT_EXCEEDED', `${label} exceeds limit`); return value; }
function timestamp(value, label, allowUndefined = false) { if (value === undefined && allowUndefined) return undefined; if (!Number.isSafeInteger(value) || value < 0) fail('INVALID_FIELD', `${label} must be a non-negative safe integer timestamp`); return value; }
function normalizeTags(value, limits) { if (value === undefined) return Object.freeze([]); if (!Array.isArray(value)) fail('INVALID_FIELD', 'tags must be an array'); return Object.freeze([...new Set(value.map((v) => text(v, 'tag', limits.maxTagBytes)))].sort()); }
function normalizeReferences(value, limits) { if (value === undefined) return Object.freeze([]); if (!Array.isArray(value)) fail('INVALID_FIELD', 'references must be an array'); return Object.freeze([...new Set(value.map((v) => text(v, 'reference', limits.maxReferenceBytes)))].sort()); }
function normalizeRecord(input, limits) { rejectAccessors(input, 'record'); const id = text(input.id, 'id', limits.maxIdBytes); const state = input.state ?? 'live'; if (!STATES.includes(state)) fail('INVALID_STATE', `Unknown state: ${state}`); const createdAt = timestamp(input.createdAt, 'createdAt'); const updatedAt = timestamp(input.updatedAt, 'updatedAt'); if (updatedAt < createdAt) fail('INVALID_FIELD', 'updatedAt cannot precede createdAt'); const expiresAt = timestamp(input.expiresAt, 'expiresAt', true); const tags = normalizeTags(input.tags, limits); const references = normalizeReferences(input.references, limits); const metadata = stable(input.metadata ?? {}, 'metadata'); if (byteLength(JSON.stringify(metadata)) > limits.maxMetadataBytes) fail('LIMIT_EXCEEDED', 'metadata exceeds limit'); return Object.freeze({ id, state, createdAt, updatedAt, expiresAt, tags, references, metadata }); }
function canonicalRecords(records, limits) { if (!Array.isArray(records) || records.length > limits.maxRecords) fail('LIMIT_EXCEEDED', 'record count exceeds limit'); const normalized = records.map((r) => normalizeRecord(r, limits)); const seen = new Set(); for (const r of normalized) { if (seen.has(r.id)) fail('DUPLICATE_RECORD', `duplicate id: ${r.id}`); seen.add(r.id); } normalized.sort((a, b) => a.id.localeCompare(b.id, 'en', { numeric: false })); return Object.freeze(normalized); }
function serializeState(records, limits) { const canonical = { format: MAGIC, version: 1, records: canonicalRecords(records, limits) }; const payload = JSON.stringify(canonical); if (byteLength(payload) > limits.maxSerializedBytes) fail('LIMIT_EXCEEDED', 'serialized state exceeds limit'); const checksum = sha256(payload); return Buffer.from(`${MAGIC}\n${JSON.stringify({ ...canonical, checksum })}\n`, 'utf8'); }
function parseState(raw, limits) { if (!(raw instanceof Uint8Array)) fail('UNSUPPORTED_VALUE', 'serialized state must be bytes'); if (raw.byteLength > limits.maxSerializedBytes) fail('LIMIT_EXCEEDED', 'serialized state exceeds limit'); const textValue = Buffer.from(raw).toString('utf8'); if (!textValue.startsWith(`${MAGIC}\n`)) fail('INVALID_STATE', 'invalid lifecycle header'); let parsed; try { parsed = JSON.parse(textValue.slice(MAGIC.length + 1).trimEnd()); } catch { fail('INVALID_STATE', 'malformed lifecycle state'); } rejectAccessors(parsed, 'state'); if (parsed.format !== MAGIC || parsed.version !== 1 || !Array.isArray(parsed.records) || typeof parsed.checksum !== 'string') fail('INVALID_STATE', 'unsupported lifecycle format'); const canonical = { format: MAGIC, version: 1, records: canonicalRecords(parsed.records, limits) }; if (parsed.checksum !== sha256(JSON.stringify(canonical))) fail('CORRUPT_STATE', 'lifecycle checksum mismatch'); return canonical.records; }
function transition(record, nextState, now) { if (!STATES.includes(nextState)) fail('INVALID_STATE', `Unknown state: ${nextState}`); if (record.state === nextState) return record; if (!ALLOWED[record.state].includes(nextState)) fail('INVALID_TRANSITION', `${record.state} -> ${nextState} is not allowed`); const updatedAt = timestamp(now, 'now'); if (updatedAt < record.updatedAt) fail('INVALID_TIME', 'now cannot precede updatedAt'); return Object.freeze({ ...record, state: nextState, updatedAt }); }
function evaluateRetention(record, policy, now) { rejectAccessors(policy, 'policy'); const time = timestamp(now, 'now'); const retainAfterMs = policy.retainAfterMs ?? null; const expireAfterMs = policy.expireAfterMs ?? null; const requiredTag = policy.requiredTag ?? null; if (retainAfterMs !== null && (!Number.isSafeInteger(retainAfterMs) || retainAfterMs < 0)) fail('INVALID_POLICY', 'retainAfterMs invalid'); if (expireAfterMs !== null && (!Number.isSafeInteger(expireAfterMs) || expireAfterMs < 0)) fail('INVALID_POLICY', 'expireAfterMs invalid'); if (requiredTag !== null) text(requiredTag, 'requiredTag', 256); const age = time - record.createdAt; if (requiredTag && !record.tags.includes(requiredTag)) return Object.freeze({ action: 'none', reason: 'tag_not_selected', age }); if (expireAfterMs !== null && age >= expireAfterMs && ALLOWED[record.state].includes('expired')) return Object.freeze({ action: 'transition', target: 'expired', reason: 'age_expired', age }); if (retainAfterMs !== null && age >= retainAfterMs && ALLOWED[record.state].includes('retained')) return Object.freeze({ action: 'transition', target: 'retained', reason: 'age_retained', age }); return Object.freeze({ action: 'none', reason: 'policy_no_match', age }); }
class ArtifactLifecycleIndex {
  constructor(options = {}) { rejectAccessors(options, 'options'); this.limits = limitsOf(options.limits ?? {}); this.file = options.file ? path.resolve(options.file) : null; this.records = new Map(); this.closed = false; }
  _assertOpen() { if (this.closed) fail('CLOSED', 'lifecycle index is closed'); }
  _snapshotArray() { return Object.freeze([...this.records.values()].sort((a, b) => a.id.localeCompare(b.id, 'en', { numeric: false }))); }
  async open() { this._assertOpen(); if (this.file) { try { const raw = await fs.readFile(this.file); for (const record of parseState(raw, this.limits)) this.records.set(record.id, record); } catch (error) { if (error?.code !== 'ENOENT') throw error; } } return this; }
  close() { this.closed = true; }
  async _persist(records) { if (!this.file) return; await fs.mkdir(path.dirname(this.file), { recursive: true }); const data = serializeState(records, this.limits); const temp = `${this.file}.${process.pid}.${Date.now()}.tmp`; await fs.writeFile(temp, data, { flag: 'wx' }); try { await fs.rename(temp, this.file); } catch (error) { try { await fs.unlink(temp); } catch {} throw error; } }
  async add(input) { this._assertOpen(); const record = normalizeRecord(input, this.limits); if (this.records.has(record.id)) fail('DUPLICATE_RECORD', `duplicate id: ${record.id}`); const next = new Map(this.records); next.set(record.id, record); await this._persist([...next.values()]); this.records = next; return record; }
  get(id) { this._assertOpen(); const key = text(id, 'id', this.limits.maxIdBytes); return this.records.get(key) ?? null; }
  async transition(id, nextState, now) { this._assertOpen(); const key = text(id, 'id', this.limits.maxIdBytes); const current = this.records.get(key); if (!current) fail('NOT_FOUND', `id not found: ${key}`); const nextRecord = transition(current, nextState, now); const next = new Map(this.records); next.set(key, nextRecord); await this._persist([...next.values()]); this.records = next; return nextRecord; }
  query(options = {}) { this._assertOpen(); rejectAccessors(options, 'query'); const limit = options.limit === undefined ? this.limits.maxResults : Math.min(options.limit, this.limits.maxResults); if (!Number.isSafeInteger(limit) || limit < 1) fail('INVALID_LIMIT', 'invalid query limit'); const state = options.state; const tag = options.tag; const olderThan = options.olderThan; const expiresBefore = options.expiresBefore; if (state !== undefined && !STATES.includes(state)) fail('INVALID_STATE', 'unknown state filter'); if (tag !== undefined) text(tag, 'tag', this.limits.maxTagBytes); timestamp(olderThan, 'olderThan', true); timestamp(expiresBefore, 'expiresBefore', true); return Object.freeze(this._snapshotArray().filter((r) => (state === undefined || r.state === state) && (tag === undefined || r.tags.includes(tag)) && (olderThan === undefined || r.updatedAt <= olderThan) && (expiresBefore === undefined || (r.expiresAt !== undefined && r.expiresAt <= expiresBefore))).slice(0, limit)); }
  retentionPlan(policy, now, options = {}) { this._assertOpen(); rejectAccessors(options, 'options'); const limit = options.limit === undefined ? this.limits.maxResults : Math.min(options.limit, this.limits.maxResults); if (!Number.isSafeInteger(limit) || limit < 1) fail('INVALID_LIMIT', 'invalid plan limit'); const plan = []; for (const record of this._snapshotArray()) { const evaluation = evaluateRetention(record, policy, now); if (evaluation.action === 'transition' && plan.length < limit) plan.push(Object.freeze({ id: record.id, from: record.state, to: evaluation.target, reason: evaluation.reason, age: evaluation.age })); } return Object.freeze(plan); }
  purgePlan(options = {}) { this._assertOpen(); rejectAccessors(options, 'options'); const limit = options.limit === undefined ? this.limits.maxResults : Math.min(options.limit, this.limits.maxResults); const olderThan = options.olderThan; if (olderThan !== undefined) timestamp(olderThan, 'olderThan'); const states = options.states === undefined ? ['expired', 'tombstoned'] : options.states; if (!Array.isArray(states) || states.some((s) => !STATES.includes(s))) fail('INVALID_STATE', 'invalid purge states'); return Object.freeze(this._snapshotArray().filter((r) => states.includes(r.state) && (olderThan === undefined || r.updatedAt <= olderThan)).slice(0, limit).map((r) => Object.freeze({ id: r.id, state: r.state, reason: 'eligible_for_dry_run_purge' }))); }
  snapshot() { this._assertOpen(); return Object.freeze({ format: MAGIC, version: 1, records: this._snapshotArray() }); }
  serialize() { this._assertOpen(); return serializeState(this._snapshotArray(), this.limits); }
  restore(serialized) { this._assertOpen(); const records = parseState(serialized, this.limits); this.records = new Map(records.map((r) => [r.id, r])); }
}
export { MAGIC, STATES, ALLOWED, DEFAULT_LIMITS, ArtifactLifecycleError, ArtifactLifecycleIndex, evaluateRetention, transition, parseState, serializeState };
